nome = input("Nome do atleta: ")
n1 = float(input("Nota_1: "))
n2 = float(input("Nota_2: "))
n3 = float(input("Nota_3: "))
n4 = float(input("Nota_4: "))
n5 = float(input("Nota_5: "))
n6 = float(input("Nota_6: "))
n7 = float(input("Nota_7: "))

notas = [n1,n2,n3,n4,n5,n6,n7]
maior = max(notas)
menor = min(notas)
notas.remove(maior)
notas.remove(menor)
soma = sum(notas)
media = float(soma/5)
notas.sort()

print("")
print("Resultado final:")
print("Atleta: " + nome)
print("Melhor nota: " + str(maior))
print("Pior nota: " + str(menor))
print("Média: " + str(round(media,2)))