n1 = int(input("Primeiro Número (inteiro): "))
n2 = int(input("Segundo Número (inteiro): "))
n3 = float(input("Terceiro Número (real): "))
print("")
print("Saída")
print("")
print("o produto do dobro do primeiro com metade do segundo é: " + str(int((2*n1)*(n2/2))))
print("A soma do triplo do primeiro com o terceiro é: " + str((3*n1)+(n3)))
print("o terceiro elevado ao cubo é: " + str(n3 ** 3))